// Shared portal API paths: used by both browser features and server routes.
(function(root){
  const routes = Object.freeze({
  "serverEnvironment": "/api/server/environment",
  "serverStatus": "/api/server/status",
  "playerMe": "/api/player/me",
  "playerLogout": "/api/player/logout",
  "playerSteamLogin": "/api/player/steam/login",
  "playerGarage": "/api/player/garage",
  "playerGarageParkPrepare": "/api/player/garage/park-prepare",
  "playerGaragePark": "/api/player/garage/park",
  "playerGarageRestorePrepare": "/api/player/garage/restore-prepare",
  "playerGarageRestore": "/api/player/garage/restore",
  "playerGarageSell": "/api/player/garage/sell",
  "playerVitals": "/api/player/vitals",
  "playerMap": "/api/player/map",
  "teleportDestinations": "/api/teleport/destinations",
  "teleportExecute": "/api/teleport/execute",
  "skinInfo": "/api/skin/info",
  "skinApply": "/api/skin/apply",
  "skinBuy": "/api/skin/buy",
  "skinPresetApply": "/api/skin/preset/apply",
  "leaderboard": "/api/leaderboard",
  "adminRolesSlots": "/api/admin/roles-slots",
  "adminPlayerInfo": "/api/admin/player-info",
  "adminAssignRoleSlots": "/api/admin/assign-role-slots",
  "adminRemoveRoleSlots": "/api/admin/remove-role-slots",
  "adminCombatLogs": "/api/admin/combat-logs",
  "adminCombatAction": "/api/admin/combat-action",
  "playerLoginManual": "/api/player/login-manual",
  "tradeData": "/api/trade/data",
  "tradeCreate": "/api/trade/create",
  "tradeAccept": "/api/trade/accept",
  "tradeDecline": "/api/trade/decline",
  "tradeCancel": "/api/trade/cancel",
  "supportMyTickets": "/api/support/my-tickets",
  "supportUnstuck": "/api/support/unstuck",
  "supportTicket": "/api/support/ticket",
  "cratesList": "/api/crates/list",
  "marketData": "/api/market/data",
  "cratesOpen": "/api/crates/open",
  "serverPlayers": "/api/server/players",
  "playerTeam": "/api/player/team",
  "referralMe": "/api/referral/me",
  "referralGenerateCode": "/api/referral/generate-code",
  "referralClaim": "/api/referral/claim",
  "playerQuests": "/api/player/quests",
  "playerQuestsClaim": "/api/player/quests/claim",
  "playerQuestsClaimAll": "/api/player/quests/claim-all",
  "casinoStats": "/api/casino/stats",
  "casinoTaiXiuPlay": "/api/casino/tai-xiu/play",
  "casinoBauCuaPlay": "/api/casino/bau-cua/play",
  "casinoDinoRacePlay": "/api/casino/dino-race/play",
  "carcassTypes": "/api/carcass/types",
  "carcassOrder": "/api/carcass/order",
  "adminCheck": "/api/admin/check",
  "adminSyncAssignments": "/api/admin/sync-assignments",
  "casino": "/api/casino",
  "mapZones": "/api/map/zones",
  "marketSellRules": "/api/market/sell-rules",
  "marketListDino": "/api/market/list-dino",
  "marketCancelListing": "/api/market/cancel-listing",
  "marketTransfer": "/api/market/transfer",
  "marketBuy": "/api/market/buy",
  "playerSteamCallback": "/api/player/steam/callback",
  "playerSessionSwitch": "/api/player/session/switch",
  "playerDaily": "/api/player/daily",
  "playerOwnedSkins": "/api/player/owned-skins",
  "serverDiets": "/api/server/diets",
  "serverLeaderboard": "/api/server/leaderboard",
  "shopDinosCatalog": "/api/shop/dinos-catalog",
  "shopBuyDino": "/api/shop/buy-dino",
  "shopSkinsCatalog": "/api/shop/skins-catalog",
  "teleportFriendCode": "/api/teleport/friend-code",
  "teleportRedeemFriend": "/api/teleport/redeem-friend"
});
  const api = Object.freeze({routes, url(path, params = {}) { const query = new URLSearchParams(params).toString(); return path + (query ? '?' + query : ''); }});
  if(typeof module === 'object' && module.exports) module.exports = api;
  else root.ST25API = api;
})(typeof globalThis === 'object' ? globalThis : this);
